"""Model for storing fraud alerts generated by the fraud scanner."""
from datetime import datetime
from typing import Optional
from uuid import uuid4

from beanie import Document, Link
from pydantic import Field

from app.models.user import User


class FraudAlert(Document):
    id: str = Field(default_factory=lambda: str(uuid4()))
    scan_id: str
    verdict: str
    fraud_score: float
    confidence: float
    signals: dict
    scanned_by: Optional[Link[User]] = None
    certificate_id: Optional[str] = None
    ip_address: Optional[str] = None
    image_hash: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "fraud_alerts"
        indexes = ["scan_id", "verdict", "created_at", "certificate_id"]
